# Common Repositories
#
# This NSL library repository is used by all example projects
#
# Note: This configuraiton assumes you have a checkout of NSL sibling to GBS
# and that you installed the NSL GBS build plugin from NSL source tree
repositories:
  - path: ../../nsl/lib
    loader: nsl-tree
