"""Xilinx ISE Dispatcher implementation"""

from __future__ import annotations
from typing import Any
from pathlib import Path

from ...base import BaseDispatcher
from ...build.context import BuildContext
from ...build.task import ResourceTypology
from . import task


class IseDispatcher(BaseDispatcher):
    """Xilinx ISE FPGA synthesis backend

    Workflow (all tasks created on first process() call with HDL sources):

    1. XST (Synthesis):
       - Creates .prj file listing all sources
       - Creates .xst command file
       - Runs xst to produce .ngc netlist

    2. NGDBUILD:
       - Takes .ngc and .ucf constraints
       - Produces .ngd (native generic database)

    3. MAP:
       - Takes .ngd
       - Produces .map.ncd and .pcf

    4. PAR (Place and Route):
       - Takes .map.ncd
       - Produces .par.ncd

    5. TRCE (Timing Report):
       - Takes .par.ncd and .pcf
       - Produces .twr timing report

    6. BITGEN:
       - Takes .par.ncd
       - Produces .bit bitstream
    """

    def __init__(
            self,
            context: BuildContext,
            vhdl_std: str,
            tool: str,
            target: dict[str, str] = {},
    ):
        super().__init__(context, "ise", tool_name=tool)
        self.output_base_name = "project"
        self.target = target
        self.device = target["part"]

        self.xst_task = None
        self.bmm_task = None
        self.net_task = None
        self.map_task = None
        self.par_task = None
        self.trce_task = None
        self.bitgen_task = None
        self.vhdl_std = vhdl_std

        if vhdl_std != "1993":
            raise ValueError("ISE has no useful support outside of VHDL-1993")

    async def process(self) -> None:
        """Process HDL sources and constraints

        Creates all tasks on first call with HDL sources.
        """

        # Get target from project config
        if not self.context.project:
            raise ValueError("No project configured")

        # Get output base name
        output_base_name = self.output_base_name or self.context.get_topcell()

        if not self.xst_task:
            await self._task_graph_create()

        await self._sources_hookup()

    async def _sources_hookup(self) -> None:
        # Add HDL input resources
        sources = list(self.context.filter_pending(file_type=["vhdl", "verilog"]))
        if sources:
            self.debug(f"Adding {len(sources)} XST sources")
        for resource in sources:
            self.xst_task.add_input(resource)

        # Add UCF input resources
        sources = list(self.context.filter_pending(file_type=["xilinx-ucf"]))
        if sources:
            self.debug(f"Adding {len(sources)} UCF sources")
        for resource in sources:
            self.debug(f"Adding netlister UCF: {resource}")
            self.net_task.add_input(resource)

    async def _task_graph_create(self) -> None:
        """Create all ISE build tasks

        Creates the full chain: XST -> NGDBUILD -> MAP -> PAR -> TRCE -> BITGEN
        """
        ise_path = Path(self.get_tool_option("path"))

        env_resource = self.context.get_resource(
            ise_path / "ISE_DS" / "settings64.sh",
            file_type="ise-settings-sh",
            typology=ResourceTypology.SOURCE
        )

        # Define intermediate file paths
        op = self.context.output_path

        def intermediate(path, file_type, **kwargs):
            return self.context.get_resource(
                path, file_type=file_type,
                typology=ResourceTypology.INTERMEDIATE,
                generated_by=self.name, **kwargs)

        # Primary build artifacts
        ngc_resource = intermediate(op / "syn" / "project.ngc", "ise-netlist-xst")
        edif_resource = intermediate(op / "syn" / "project.edif", "ise-netlist")
        bmm_resource = intermediate(op / "func" / "project.bmm", "ise-bmm")
        ngd_resource = intermediate(op / "func" / "project.ngd", "ise-netlist-functional")
        map_resource = intermediate(op / "map" / "project.map.ncd", "ise-netlist-partial", library="work")
        pcf_resource = intermediate(op / "map" / "project.map.pcf", "ise-physical-constraints")
        par_resource = intermediate(op / "par" / "project.par.ncd", "ise-netlist-full", library="work")
        twr_resource = intermediate(op / "par" / "project.twr", "ise-timing-report")
        bit_resource = self.context.get_resource(
            op / "project.bit", file_type="bitstream",
            typology=ResourceTypology.OUTPUT, generated_by=self.name)

        # Report side-products (always generated by their respective tools)
        xst_log_resource = intermediate(op / "syn" / "xst_run.log", "ise-xst-log")
        map_report_resource = intermediate(op / "map" / "project.map.mrp", "ise-map-report")
        par_log_resource = intermediate(op / "par" / "project.par.par", "ise-par-log")
        par_pad_resource = intermediate(op / "par" / "project.par_pad.csv", "ise-par-pad-csv")

        # Run XST synthesis
        self.xst_task = task.Xst(
            dispatcher=self,
            device=self.device,
            inputs=[env_resource],
            outputs=[ngc_resource, xst_log_resource],
        )
        self.attach_definition_dependencies(self.xst_task)

        # Generate BMM file (placeholder)
        self.bmm_task = task.BmmGenerate(
            dispatcher=self,
            outputs=[bmm_resource],
        )

        # Convert Netlist
        self.net_task = task.NetlistConvert(
            dispatcher=self,
            inputs=[env_resource, ngc_resource, bmm_resource],
            outputs=[ngd_resource],
        )
        self.edif_task = task.EdifConvert(
            dispatcher=self,
            inputs=[env_resource, ngc_resource],
            outputs=[edif_resource],
        )

        # Physical Mapping
        self.map_task = task.Map(
            dispatcher=self,
            device=self.device,
            inputs=[env_resource, ngd_resource],
            outputs=[map_resource, pcf_resource, map_report_resource],
        )

        # Place and Route
        self.par_task = task.Par(
            dispatcher=self,
            inputs=[env_resource, map_resource],
            outputs=[par_resource, par_log_resource, par_pad_resource],
        )

        # Run Timing Analysis
        self.trce_task = task.Trce(
            dispatcher=self,
            inputs=[env_resource, par_resource, pcf_resource],
            outputs=[twr_resource],
        )

        # Run BITGEN
        self.bitgen_task = task.Bitgen(
            dispatcher=self,
            inputs=[env_resource, par_resource],
            outputs=[bit_resource],
        )

        # Create report aggregation tasks for any requested aggregate outputs
        for dest in self.context.filter_pending(file_type="ise-synthesis-report"):
            task.AggregateReport(
                dispatcher=self,
                name="ise_synthesis_report",
                title="ISE Synthesis Report",
                inputs=[xst_log_resource, map_report_resource],
                outputs=[dest],
            )

        for dest in self.context.filter_pending(file_type="ise-pnr-report"):
            task.AggregateReport(
                dispatcher=self,
                name="ise_pnr_report",
                title="ISE PnR Report",
                inputs=[par_log_resource, par_pad_resource, twr_resource],
                outputs=[dest],
            )

        # Add outputs to pending queue
