"""QuestaSim/ModelSim build tasks

Task implementations for QuestaSim/ModelSim simulation flow.
Generates TCL batch scripts and shell wrapper scripts.
"""

from __future__ import annotations
from pathlib import Path
from collections import defaultdict

from ...build.task import Task, BuildError


class GenerateBatchScript(Task):
    """Generate QuestaSim TCL batch script

    Creates a TCL script that:
    1. Creates libraries (vlib)
    2. Compiles VHDL/Verilog sources (vcom/vlog)
    3. Runs simulation (vsim)
    """

    # VHDL version argument mapping
    VHDL_VERSION_MAP = {
        "1987": "87",
        "87": "87",
        "1993": "93",
        "93": "93",
        "2002": "2002",
        "02": "2002",
        "2008": "2008",
        "08": "2008",
        "2019": "2019",
        "19": "2019",
    }

    def __init__(
        self,
        dispatcher: "Dispatcher",
        vhdl_std: str,
        inputs: list,
        outputs: list,
    ):
        super().__init__(
            dispatcher=dispatcher,
            name="questa_batch_script",
            inputs=inputs,
            outputs=outputs,
            description="Generate QuestaSim batch script"
        )
        self.vhdl_std = vhdl_std

    def _get_vhdl_version_arg(self, variant: str | None) -> str:
        """Get VHDL version argument for vcom

        Args:
            variant: VHDL variant from source metadata

        Returns:
            Version argument (e.g., "93", "2008")
        """
        if variant:
            return self.VHDL_VERSION_MAP.get(variant, self.vhdl_std)
        return self.VHDL_VERSION_MAP.get(self.vhdl_std, "93")

    async def work(self) -> None:
        """Generate the TCL batch script"""
        topcell = self.dispatcher.context.get_topcell()
        top_lib = self.dispatcher.context.get_topcell_library() or "work"

        # Group inputs by library, preserving order
        inputs_by_library = defaultdict(list)
        seen_libraries = []

        for resource in self.inputs:
            lib = resource.library or 'work'
            if lib not in seen_libraries:
                seen_libraries.append(lib)
            inputs_by_library[lib].append(resource)

        # Build TCL script
        lines = []
        lines.append("# QuestaSim/ModelSim batch script generated by GBS")
        lines.append("")

        # Create libraries
        lines.append("# Create libraries")
        for library in seen_libraries:
            lines.append(f"vlib -quiet {library}")
        lines.append("")

        # Compile sources
        lines.append("# Compile sources")
        for library in seen_libraries:
            for resource in inputs_by_library[library]:
                file_type = resource.file_type
                file_path = resource.path.resolve()

                if file_type == 'vhdl':
                    variant = resource.file_type_version
                    vhdl_ver = self._get_vhdl_version_arg(variant)
                    lines.append(
                        f"vcom -quiet -nologo -work {library} -{vhdl_ver} "
                        f"-noautoorderrefresh {{{file_path}}}"
                    )
                elif file_type == 'verilog':
                    lines.append(
                        f"vlog -quiet -nologo -work {library} {{{file_path}}}"
                    )

        lines.append("")

        # Simulation run
        lines.append("# Run simulation")
        lines.append(f"vsim -quiet -work {top_lib} {topcell} +dumpports+nocollapse")
        lines.append("onfinish default")
        lines.append("run -all")
        lines.append('puts "Error level [coverage attribute -name TESTSTATUS -concise]"')
        lines.append("quit -f -code [coverage attribute -name TESTSTATUS -concise]")

        # Write script
        script_path = self.outputs[0].path
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text("\n".join(lines) + "\n")

        self.info(f"Generated batch script: {script_path}")


class GenerateSimulatorScript(Task):
    """Generate QuestaSim simulator shell script

    Creates a shell script that invokes vsim with the batch script.
    Uses absolute paths so the script can be copied and run from elsewhere.
    """

    def __init__(
        self,
        dispatcher: "Dispatcher",
        vsim_executable: Path,
        inputs: list,
        outputs: list,
    ):
        super().__init__(
            dispatcher=dispatcher,
            name="questa_simulator_script",
            inputs=inputs,
            outputs=outputs,
            description="Generate QuestaSim simulator script"
        )
        self.vsim_executable = vsim_executable

    async def work(self) -> None:
        """Generate the simulator shell script"""
        # Get batch script path from inputs
        batch_script = None
        for resource in self.inputs:
            if resource.file_type == 'questa-batch-script':
                batch_script = resource.path.resolve()
                break

        if batch_script is None:
            raise BuildError("No batch script found in inputs")

        # Build shell script content
        script_content = f"""#!/bin/sh

exec {self.vsim_executable} -batch -quiet -do {batch_script}
"""

        # Write script
        script_path = self.outputs[0].path
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(script_content)
        script_path.chmod(0o755)

        self.info(f"Generated simulator script: {script_path}")
